### ISSUE TITLE
Add ability to dig trenches by multiple players

### ISSUE THREAD

**Issue by gandjustas** [gruppe-adler/grad_trenches#41]
Two or more player come to same trench, use action "continue digging" and reduces time to dig.

We play with very high dig times - 15 minutes for vehicle trench. It would be great to add ability to dig one vehicle trench by full crew of tank.

**Comment by gandjustas** [comment]
You are already use your own function continueDiggingTrench, you can do collective digging in this function.

**Comment by chris579** [comment]
Right, that's because we have to set the texture there. But allowing multiple people to build the trench is not trivial as this would require syncing the status and modifying who is able to build the trench. This may need a rewrite how trenches are built. Therefore this is out of scope for a mod that is retexturing trenches (even tho we already implemented too much and therefore I have to pull the brake at some point).
